name: scaffold_factory
description: A flutter library to build and customize a screen with a simple and flexible configuration.
version: 0.1.0
author: Erfan Jazeb Nikoo
homepage: https://github.com/erfanjazebnikoo/scaffold_factory

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.erfanjazebnikoo.scaffoldfactory
    pluginClass: ScaffoldFactoryPlugin

