name: scaffold_factory
description: A flutter library to build and customize a screen with a simple and flexible configuration.
version: 0.7.1
author: Erfan Jazeb Nikoo <erfan.jazebnikoo@gmail.com>
homepage: https://github.com/erfanjazebnikoo/scaffold_factory

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor: ^0.1.1
  event_bus: ^1.0.1
  url_launcher: ^4.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.erfanjazebnikoo.scaffoldfactory
    pluginClass: ScaffoldFactoryPlugin

